# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-26 19:29
from __future__ import unicode_literals

import Posts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('content', models.TextField(max_length=256)),
                ('image', models.ImageField(blank=True, null=True, upload_to=Posts.models.upload_location)),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
