# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-09 09:43
from __future__ import unicode_literals

import Posts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorDetailModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=56, null=True)),
                ('work', models.TextField(default='', max_length=512, null=True)),
                ('address', models.TextField(default='', max_length=512, null=True)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to=Posts.models.upload_location_profile_pic)),
                ('author_bio', models.TextField(default='', max_length=512, null=True)),
                ('Author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CommentsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, max_length=256, null=True)),
                ('timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('Author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=120)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('content', models.TextField(default='', max_length=1024)),
                ('image', models.ImageField(null=True, upload_to=Posts.models.upload_location_post)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('Author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(default=0, related_name='postlikes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
