# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-09 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentsmodel',
            name='content',
            field=models.TextField(blank=True, max_length=258, null=True),
        ),
    ]
