# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-09 10:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0002_auto_20170809_0315'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentsmodel',
            name='Post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Posts.PostModel'),
        ),
    ]
