# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-03 21:34
from __future__ import unicode_literals

import Posts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0002_auto_20170803_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='image',
            field=models.ImageField(null=True, upload_to=Posts.models.upload_location_post),
        ),
    ]
