# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-26 17:18
from __future__ import unicode_literals

import Posts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0002_auto_20170726_0236'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='image',
            field=models.ImageField(blank=True, height_field=150, null=True, upload_to=Posts.models.upload_location, width_field=150),
        ),
    ]
