# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-10 06:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0003_commentsmodel_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentsmodel',
            name='Post',
        ),
    ]
