# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-05 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0003_auto_20170804_0304'),
    ]

    operations = [
        migrations.AddField(
            model_name='authordetailmodel',
            name='full_name',
            field=models.CharField(max_length=56, null=True),
        ),
    ]
