# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-06 18:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Posts', '0004_authordetailmodel_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='likes',
            field=models.ManyToManyField(default=0, related_name='postlikes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='authordetailmodel',
            name='full_name',
            field=models.CharField(blank=True, max_length=56, null=True),
        ),
    ]
