# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-09 06:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Posts', '0004_authordetailmodel_full_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, max_length=256, null=True)),
                ('timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('Author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='postmodel',
            name='category',
        ),
        migrations.AddField(
            model_name='postmodel',
            name='likes',
            field=models.ManyToManyField(default=0, related_name='postlikes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='authordetailmodel',
            name='address',
            field=models.TextField(default='', max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='authordetailmodel',
            name='author_bio',
            field=models.TextField(default='', max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='authordetailmodel',
            name='full_name',
            field=models.CharField(blank=True, max_length=56, null=True),
        ),
        migrations.AlterField(
            model_name='authordetailmodel',
            name='work',
            field=models.TextField(default='', max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='content',
            field=models.TextField(default='', max_length=1024),
        ),
    ]
