# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-26 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0005_auto_20170726_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
