# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-06 22:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0005_auto_20170807_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authordetailmodel',
            name='address',
            field=models.TextField(default='', max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='authordetailmodel',
            name='author_bio',
            field=models.TextField(default='', max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='authordetailmodel',
            name='work',
            field=models.TextField(default='', max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='content',
            field=models.TextField(default='', max_length=1024),
        ),
    ]
