# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-10 07:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0005_auto_20170810_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentsmodel',
            name='Author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
