# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-10 08:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0006_auto_20170810_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentsmodel',
            name='Author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Posts.AuthorDetailModel'),
        ),
    ]
