# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-08 03:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0006_auto_20170807_0335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmodel',
            name='category',
        ),
    ]
