# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-30 23:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0006_auto_20170728_2122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmodel',
            name='updated',
        ),
        migrations.AddField(
            model_name='postmodel',
            name='category',
            field=models.CharField(choices=[('Travel', 'Travel'), ('Sports', 'Sports'), ('Life', 'Life'), ('Education', 'Education'), ('Others', 'Others')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='content',
            field=models.TextField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='title',
            field=models.CharField(default='', max_length=120),
        ),
    ]
