# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-09 09:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0007_remove_postmodel_category'),
        ('Posts', '0005_auto_20170808_2341'),
    ]

    operations = [
    ]
