# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-30 23:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0007_auto_20170731_0448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
