# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-01 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0008_auto_20170731_0449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='category',
            field=models.CharField(choices=[('Travel', 'Travel'), ('Fashion', 'Fashion'), ('Life', 'Life'), ('Education', 'Education'), ('Entertainment', 'Entertainment')], max_length=10, null=True),
        ),
    ]
