# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-14 09:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0009_post_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_views',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 14, 15, 7, 57, 584464)),
        ),
    ]
